Allow Compilations to have missing sources
trufflesuite/truffle pull request #3529
Opened 2020-11-13 01:09 UTC by gnidan

This removes the non-nullability requirement for source and processed source inputs, as well as fixes the resolvers to handle the case where these are null.

This addresses the situation where @truffle/workflow-compile reports `null` paths for particular source indexes

2020-11-16 20:07 UTC, fainashalts requested changes
Can you add a test with an empty source? Or is that overkill?

I also wonder what scenario you're imagining this is needed for - factory patterns? Something else?

2020-11-22 22:41 UTC, gnidan commented
> I also wonder what scenario you're imagining this is needed for - factory patterns? Something else?

This arises due to the way compile-solidity sets things up. Let's say you have sources `A.sol`, `B.sol`, and `C.sol`, none of which import each other. If you compile them all, then make a change to `B.sol` and run `truffle compile` again, you'll get the resulting sourceIndexes `[null, "B.sol", null]`. So we have to handle that in @truffle/db.

> Can you add a test with an empty source? Or is that overkill?

I'm not sure how best to add a unit test for this... it seems like this might make a better scenario test, but we'd have to wait for `truffle-db-mvp` for that. What do you think?

2020-12-08 08:27 UTC, fainashalts commented
That seems reasonable!

2020-12-08 08:28 UTC, fainashalts approved these changes
LGTM!

2020-12-08 13:36 UTC, gnidan commented
Thanks!

2020-12-08 13:36 UTC, merged