Internal improvement: Use MetaMask's web3-provider-engine package instead of our fork
trufflesuite/truffle pull request #4416
Opened 2021-11-10 16:13 UTC by eggplantzzz

This PR gets Truffle off of Truffle's fork of web3-provider-engine and back on to MetaMask's package. Eventually we should probably re-architect this package to use newer libraries.

2021-11-12 12:27 UTC, cds-amal commented
Note: this PR fixes #3777 and #4143

2021-11-12 13:43 UTC, cds-amal requested changes
I'm excited about this @eggplantzzz ! I noticed a small typescript thing and can't wait to deprecate/archive our **trufflesuite/web3-provider-engine**

2021-11-12 13:43 UTC, cds-amal commented on packages/hdwallet-provider/src/index.ts
> +import WebsocketProvider from "web3-provider-engine/subproviders/websocket";
The current subprovider declaration files ([filters.d.ts and co](https://github.com/trufflesuite/truffle/blob/bump-web3-provider-engine/packages/hdwallet-provider/typings/web3-provider-engine/subproviders/filters.d.ts#L1)) should be updated to drop the  **trufflesuite** scope. This should allow removing the _ts-ignore_ directive

2021-11-17 21:34 UTC, eggplantzzz commented
It seems like this should maybe be a breaking change for hdwallet-provider since the typing for the `send` and `sendAsync` methods has changed slightly?

2021-12-01 13:08 UTC, cds-amal approved these changes
Looks good!

2021-12-02 14:54 UTC, merged