Feature/4838 walletconnect wagmi
trufflesuite/truffle pull request #4926
Opened 2022-03-23 03:15 UTC by michaeljohnbennett

Initial POC on integrating WAGMI and WalletConnect into the dashboard codebase.

Still to do some testing on the walletconnect side against some of the wallets but normal metamask code is working as expected no we fixed a few things with the provider library selectors/hooks in the code.

2022-03-24 01:16 UTC, michaeljohnbennett commented
@dkillen will be doing a final bit of log cleanup and then this will be good to go.

Generally the code is good for review. We will be cleaning up a few log elements prior to it being read to merge.

2022-03-29 19:02 UTC, MicaiahReid requested changes

2022-03-29 19:02 UTC, MicaiahReid commented on packages/dashboard/src/utils/utils.ts
> +  const ensName = await reverseLookup(provider, address);
Did you get this working? It seems to only be returning `undefined` for me, and I have reverse lookup setup.

2022-03-29 19:04 UTC, MicaiahReid reviewed
There were some stylistic changes (increasing the Button size which increases the header height) that I'm not too picky about, but I'd definitely want more eyes on. Since we'll have a lot of dashboard changes coming through from the task force, I want to be sure we're being stylistically consistent.

2022-03-31 01:44 UTC, michaeljohnbennett commented
@MicaiahReid prettier ran, button sizing fixed.

2022-03-31 01:49 UTC, michaeljohnbennett reviewed
fixes made as per @MicaiahReid's feedback.

2022-03-31 01:49 UTC, michaeljohnbennett commented on packages/dashboard/src/components/common/Button.tsx
> +      className="rounded p-2 mx-2 bg-truffle-blue text-truffle-brown uppercase hover:bg-white"
@MicaiahReid reverted the change in this button.

2022-03-31 01:49 UTC, michaeljohnbennett commented on packages/dashboard/src/components/Header/Header.tsx
> +          <img src={"/truffle-logomark.svg"} width="32px" alt={'Truffle Logo'}/>
all fixed.

2022-04-01 12:32 UTC, MicaiahReid approved these changes
Looks good to me! If we want to get this merged sooner, maybe we could pull out the ENS name bit for another PR? I suppose there's no harm done in it not working currently, so maybe we can leave it in and add an issue to get it working ¯\_(ツ)_/¯

2022-04-03 23:58 UTC, michaeljohnbennett commented
lets leave it in and get people trying it, it might be a simple fix once we have a few people playing with it, we can pair on this once merged if you have an ENS we can test with.

2022-04-03 23:58 UTC, merged