improve default truffle-config.js readability
trufflesuite/truffle pull request #5047
Opened 2022-04-22 22:39 UTC by davidmurdoch

2022-04-22 23:47 UTC, haltman-at approved these changes
Makes sense to me.  Thanks!

2022-04-27 08:36 UTC, cds-amal requested changes
Oops, missed this.

2022-04-27 08:36 UTC, cds-amal commented on packages/core/lib/commands/init/initSource/truffle-config.js
> +    // Note: It's important to wrap the provider as a function to ensure truffle uses a new provider every time.
Uses a new provider every time is ambiguous. I would rather leave it as the suggestion below and expand the reasoning in our documentation. 

```suggestion
    // Note: It's important to wrap the provider as a function.
```

2022-04-27 13:09 UTC, eggplantzzz approved these changes
I like this.

2022-05-17 23:32 UTC, merged