Update @truffle/core in truffle and update yarn.lock
trufflesuite/truffle pull request #5380
Opened 2022-07-29 21:24 UTC by davidmurdoch

There are some issues with Truffle release 5.5.24:

 * @truffle/core's version was not bumped in truffle/package.json devDeps appropriately
 * both truffle develop and master (post release) fail in CI, not getting past yarncheck

I think this PR will fix both of these issues and get things working again.

(but a proper post-mortem should be done)

2022-07-30 03:30 UTC, haltman-at approved these changes
Yikes, thanks!

2022-07-30 21:22 UTC, cds-amal approved these changes
Thanks, @davidmurdoch!

Yikes! I don't think those scoped truffle modules belong in `yarn.lock` because of how lerna bootstraps to resolve truffle dependencies. The exceptions are:
 - `@truffle/preserve` because it is in a different repo and is resolved via npm-registry
 -  external packages that have scoped truffle modules as dependencies, like `abi-to-sol`

```console
$ grep -C 5 "@truffle/" yarn.lock

"@truffle/preserve@^0.2.7":
  version "0.2.7"
  resolved "https://registry.yarnpkg.com/@truffle/preserve/-/preserve-0.2.7.tgz#fd149e4d0f1594e400fea3453c898362655d8588"
  integrity sha512-A5pRuFre9IR2m2BB1JMF9CItgUSwR2eRhqHU2ltvPjWHNxbGAo4tMZat+124hed6zDBUduYsjmV5Yr5wo7kF8g==
  dependencies:
    spinnies "^0.5.1"
--
abi-to-sol@^0.6.2:
  version "0.6.2"
  resolved "https://registry.yarnpkg.com/abi-to-sol/-/abi-to-sol-0.6.2.tgz#e3c36e3810dd2131a9fdcdde59445d2b481de14b"
  integrity sha512-FZpqMLiatNU3YYheEtoQKAPywRoGDVecs75Nc5j4SwVDPLnBOY4oNskWaFtct1lInmDLctZsPE+GlyAckCnUWw==
  dependencies:
    "@truffle/abi-utils" "^0.2.2"
    "@truffle/codec" "^0.13.2"
    "@truffle/contract-schema" "^3.3.1"
    ajv "^6.12.5"
    better-ajv-errors "^0.8.2"
    neodoc "^2.0.2"
    semver "^7.3.5"
    source-map-support "^0.5.19"
```

2022-08-01 01:04 UTC, cds-amal requested changes
Putting an x here because I think there are some more things to fix. Commit 7a9c5742 introduced some changes to `@truffle/core`'s dependencies that we should review. There may be other packages that are similarly affected.

NOTE:  I didn't spend a lot of time on this, but saw something suspicious and wanted to mention it.

| package|truffle@5.5.23|7a9c5742|truffle@5.5.24|
|-|-|-|-|
| @truffle/artifactor | ^4.0.162 | ^4.0.161 | ^4.0.163 |
| @truffle/box | ^2.1.53 | ^2.1.52 | ^2.1.54 |
| @truffle/codec | ^0.13.3 | ^0.13.2 | ^0.13.2 :eyes:|
| @truffle/compile-solidity | ^6.0.36 | ^6.0.35 | ^6.0.37 |
| @truffle/config | ^1.3.33 | ^1.3.32 | ^1.3.34 |
| @truffle/contract | ^4.5.18 | ^4.5.17 | ^4.5.19 |
| @truffle/dashboard | ^0.1.10 | ^0.1.9 | ^0.1.9 :eyes: |
| @truffle/debug-utils | ^6.0.28 | ^6.0.27 | ^6.0.29 |
| @truffle/debugger | ^11.0.1 | ^11.0.0 | ^11.0.2 |
| @truffle/decoder | ^5.2.21 | ^5.2.20 | ^5.2.22 |
| @truffle/deployer | ^3.2.89 | ^3.2.88 | ^3.2.90 |
| @truffle/environment | ^0.2.116 | ^0.2.115 | ^0.2.117 |
| @truffle/expect | ^0.1.2 | ^0.1.1 | ^0.1.1 :eyes: |
| @truffle/fetch-and-compile | ^0.5.11 | ^0.5.10 | ^0.5.12 |
| @truffle/interface-adapter | ^0.5.19 | ^0.5.20-typescript-migrations.0 | ^0.5.20 |
| @truffle/migrate | ^3.3.3 | ^3.3.2 | ^3.3.4 |
| @truffle/plugins | ^0.2.8 | ^0.2.7 | ^0.2.7 :eyes: |
| @truffle/provider | ^0.2.57 | ^0.2.58-typescript-migrations.0 | ^0.2.58 |
| @truffle/require | ^2.0.102 | ^2.1.0-typescript-migrations.0 | ^2.1.0 |

2022-08-01 06:31 UTC, benjamincburns commented
> Commit [7a9c574](https://github.com/trufflesuite/truffle/commit/7a9c5742f277d501eeffa3fdf4d169ba10eb92ee) introduced some changes to `@truffle/core`'s dependencies that we should review.

@cds-amal This was my fault. Many of the changes in that commit were merge conflicts that resulted from me doing the dist-tag release, with a normal release going out in the interim. It looks like in many cases I took the change where I just dropped the dist-tag from the version number, but for some reason in `packages/core/package.json` I rolled some version numbers back.

I don't recall now which of these were handled automatically, and which were selected manually. I'll go through them all now and see if I can come up with a set of corrections.

I think to fix this I need to write a script that does something along the lines of:

```javascript
for (const sourcePackage of packages) {
  for (const dependantPackage in packages) {
    if (dependantPackage.dependsOn(sourcePackage) && ! dependantPackage.getDependencyVersionRange(sourcePackage).contains(sourcePackage.version)) {
      console.log(`${dependantPackage.name} is dependent on ${sourcePackage.name}, but version ${sourcePackage.version} is not contained in range '${dependantPackage.getDependencyVersionRange(sourcePackage.name)}'`);
    }
  }
}
```

I'll attempt that now. Sorry about this mess!

2022-08-01 07:22 UTC, cds-amal commented
>Many of the changes in that commit were merge conflicts that resulted from me doing the dist-tag release, with a normal release going out in the interim

Yea, our process around this should be more clearly defined and documented. IMHO, this is a win @benjamincburns. 

This script is a good idea, though I think the loop's inner logic should validate the invariant that all truffle scoped packages should resolve to the caret-ed current version of said scoped package.

2022-08-01 09:38 UTC, benjamincburns commented
> This script is a good idea, though I think the loop's inner logic should validate the invariant that all truffle scoped packages should resolve to the caret-ed current version of said scoped package.

Great minds think alike :-)

See #5384

2022-08-01 10:01 UTC, benjamincburns commented
Ah, I misunderstood your last comment. My script just verifies that a truffle-namespaced dependency _can_ resolve to the local package version given the range used to express said dependency.

Is it a problem for our builds/publish process if say `@truffle/core` has a dependency defined like `"@truffle/require": "^2.1.0"` but the current version of `@truffle/require` is `2.1.1`? I would've thought not, as `^2.1.0` evaluates to `>= 2.1.0 <3.0.0`, but I suppose I could imagine old local package versions being written to `yarn.lock` might ruin that for us...

2022-08-01 10:12 UTC, benjamincburns commented
I updated the script to output a warning whenever the range isn't exactly the carrotted current version.

Here is the output for current `develop`:

```
Warning: Package "@truffle/core" depends on "@truffle/codec@^0.13.2", but range has not been updated for version 0.13.3
Warning: Package "@truffle/core" depends on "@truffle/dashboard@^0.1.9", but range has not been updated for version 0.1.10
Warning: Package "@truffle/core" depends on "@truffle/expect@^0.1.1", but range has not been updated for version 0.1.2
Warning: Package "@truffle/core" depends on "@truffle/plugins@^0.2.7", but range has not been updated for version 0.2.8
Warning: Package "truffle" depends on "@truffle/core@^5.5.23", but range has not been updated for version 5.5.24
```

2022-08-01 10:28 UTC, benjamincburns commented
I also fixed those warnings in fad00988d (included in #5384)

2022-08-01 10:35 UTC, benjamincburns approved these changes
I think we can merge this one, as #5384 should fix the other issues that @cds-amal mentioned.

2022-08-01 15:28 UTC, davidmurdoch commented
@cds-amal @benjamincburns If you all come to a resolution on this feel free to merge (or close) on my behalf.

2022-08-01 21:14 UTC, gnidan approved these changes

2022-08-01 22:09 UTC, cds-amal approved these changes

2022-08-01 22:09 UTC, merged